// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AvaloniaToolkit
{
    internal sealed partial class Vsix
    {
        public const string Id = "AvaloniaToolkit.c46b93c6-e76c-4673-8595-65711a00be75";
        public const string Name = "AvaloniaToolkit";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Bin Dong";
        public const string Tags = "";
    }
}
