// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AvaloniaToolkit
{
    internal sealed partial class Vsix
    {
        public const string Id = "AvaloniaToolkit.c46b93c6-e76c-4673-8595-65711a00be75";
        public const string Name = "Avalonia Toolkit";
        public const string Description = @"Create Avalonia boilerplate code.";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Dong Bin";
        public const string Tags = "";
    }
}
