// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AvaloniaToolkit
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string AvaloniaToolkitString = "0cd2df26-31e3-4522-bbda-7c6a9b47152e";
        public static Guid AvaloniaToolkit = new Guid(AvaloniaToolkitString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyAddMenuGroup = 0x0001;
        public const int MyAddMenu = 0x0002;
        public const int AddConverterCommand = 0x0101;
        public const int AddViewModelCommand = 0x0102;
        public const int AddDataTemplateCommand = 0x0103;
    }
}